accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/', views.profile, name='profile'), 
    path('<str:username>/follows/', views.follows, name='follows'),
]

insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('', views.main, name='main'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:id>/likes/', views.likes, name='likes'),
    path('<int:id>/', views.detail, name='detail'),
    path('<int:post_id>/comments/create/', views.comment_create, name='comment_create'),
    
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django_resized import ResizedImageField
# Create your models here.
class User(AbstractUser):
    profile_image = ResizedImageField(
        size=[500,500],
        crop=['middle','center'],
        upload_to='profile',
    )

    followings = models.ManyToManyField('self', related_name='followers', symmetrical=False)

posts/models.py
from django.db import models
from django_resized import ResizedImageField
from django.conf import settings
# Create your models here.
class Post(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # image = models.ImageField(upload_to='image/%Y/%m')
    image = ResizedImageField(
        size=[500,500],
        crop=['middle','center'],
        upload_to='image/%Y/%m',
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')

class Comment(models.Model):
    content = models.CharField(max_length=70)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from . models import User
class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'profile_image', )

class CustomAuthenticationForm(AuthenticationForm):
    pass

posts/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        # fields = '__all__'
        exclude = ('user', 'like_users')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('post',)

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomAuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .models import User

# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('posts:index')
    else:
        form = CustomUserCreationForm()
    
    context = {
        'form':form,
    }

    return render(request, 'accounts_form.html', context)

def login(request):
    if request.method == "POST":
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request,user)

            return redirect('posts:index')
    else:
        form = CustomAuthenticationForm()

    context = {
        'form': form,
    } 

    return render(request, 'accounts_form.html', context)

def logout(request):
    auth_logout(request)
    return redirect('accounts:login')

def profile(request, username):
    user_info = User.objects.get(username=username)
    context = {
        'user_info': user_info,
    }
    return render(request, 'profile.html', context)

def follows(request, username):
    me = request.user
    you = User.objects.get(username=username)

    # 이미 팔로잉하는 경우
    if you in me.followings.all(): 
    # if me in you.followers.all():
        me.followings.remove(you)
    # 아직 팔로잉 아닌 경우
    else:
        me.followings.add(you)

    return redirect('accounts:profile', username=username)

insta/views.py
from django.shortcuts import redirect

def main(request):
    return redirect('posts:index')

posts/views.py
from django.shortcuts import render, redirect
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    posts = Post.objects.all().order_by('-id')

    context = {
        'posts': posts,
    }
    return render(request, 'index.html', context)

def detail(request, id):
    post = Post.objects.get(id=id)
    form = CommentForm

    context = {
        'post': post,
        'form': form,
    }
    return render(request, 'detail.html', context)


def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:index')
    else:
        form = PostForm()

    context = {
        'form':form,
    }

    return render(request, 'form.html', context)

@login_required
def likes(request, id):
    user = request.user 
    post = Post.objects.get(id=id)

    # 이미 좋아요 누른 경우
    # if post in user.like_posts.all():
    if user in post.like_users.all():
        post.like_users.remove(user)

    # 좋아요 아직 안누른 경우
    else:
        post.like_users.add(user)
        # user.like_posts.add(post)

    return redirect('posts:index')

@login_required
def comment_create(request, post_id):
    form = CommentForm(request.POST)

    if form.is_valid():
        comment = form.save(commit=False)

        comment.post_id = post_id
        comment.save()

        return redirect('posts:detail', id=post_id)

accounts/templates/accounts_form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit">
    </form>
{% endblock %}

accounts/templates/profile.html
{% extends 'base.html' %}

{% block body %}
    <div class="row">
        <div class="col-4">
            {% if user_info.profile_image %}
                <img src="{{ user_info.profile_image.url }}" alt="" class="rounded-circle img-fluid">
            {% else %}
                <img src="/media/profile/default.jpeg" alt="" class="rounded-circle img-fluid">
            {% endif %}

        </div>
        <div class="col-8">
            <div class="row">
                <div class="col-3">{{ user_info }}</div>

                {% if user != user_info %}
                <div class="col-4">
                    
                    {% if user in user_info.followers.all %}
                    <a href="{% url 'accounts:follows' username=user_info %}" class="btn btn-light">following</a>
                    {% else %}
                    <a href="{% url 'accounts:follows' username=user_info %}" class="btn btn-primary">follow</a>
                    {% endif %}
                </div>
                {% endif %}

            </div>
            <div class="row">
                <div class="col">게시물 {{ user_info.post_set.all|length }}</div>
                <div class="col">팔로워 {{ user_info.followers.all|length }}</div>
                <div class="col">팔로우 {{ user_info.following.all|length }}</div>
            </div>
        </div>
    </div>

    <div class="row row-cols-3">
        {% for post in user_info.post_set.all %}
            <div class="col">
                <div class="card">
                    <img src="{{ post.image.url }}" alt="">
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

posts/templates/_card.html
<div class="card my-5 col-12 col-md-6">
    <div class="card-header">
        {% if post.user.profile_image %}
            <img src="{{ post.user.profile_image.url }}" alt="" class="rounded-circle" width="30px">
        {% else %}
            <img src="/media/profile/default.jpeg" alt="" class="rounded-circle" width="30px">
        {% endif %}
        <a href="{% url 'accounts:profile' username=post.user %}" class="text-reset text-decoration-none">{{post.user}}</a>
    </div>
    <img src="{{ post.image.url }}" alt="">
    <div class="card-body">
        <a href="{% url 'posts:likes' id=post.id %}" class="text-reset text-decoration-none">
            {% if user in post.like_users.all %}
                <i class="bi bi-heart-fill" style="color:red"></i>
            {% else %}
                <i class="bi bi-heart"></i>
            {% endif%}
        </a> {{ post.like_users.all|length }}명이 종아합니다.
        <p class="card-text">{{ post.content }}</p>
        <a href="{% url 'posts:detail' id=post.id %} ">댓글 확인하기</a>

    </div>
</div>

posts/templates/detail.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block body %}
<div class="card mb-3">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="{{ post.image.url }}" class="img-fluid rounded-start" alt="">
        </div>
        <div class="col-md-8">
        <div class="card-body">
            <h5 class="card-title">
                {% if post.user.profile_image %}
                    <img src="{{ post.user.profile_image.url }}" alt="" class="rounded-circle" width="30px">
                {% else %}
                    <img src="/media/profile/default.jpeg" alt="" class="rounded-circle" width="30px">
                {% endif %}
                    <a href="{% url 'accounts:profile' username=post.user %}">{{post.user}}</a>
            </h5>
            <p class="card-text">{{ post.content }}</p>
            <p class="card-text"><small class="text-body-secondary"></small></p>
            <a href="{% url 'posts:likes' id=post.id %}" class="text-reset text-decoration-none">
                {% if user in post.like_users.all %}
                    <i class="bi bi-heart-fill" style="color:red"></i>
                {% else %}
                    <i class="bi bi-heart"></i>
                {% endif%}
            </a> {{ post.like_users.all|length }}명이 종아합니다.
            <hr>
            <form action="{% url 'posts:comment_create' post_id=post.id %}" method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="col-10">
                        {% bootstrap_form form show_label=False %}
                    </div>
                    <div class="col-2">
                        <input type="submit" class="btn btn-primary">
                    </div>
                </div>
            </form>
            <hr>
            {% for comment in post.comment_set.all %}
                <p>{{ comment.content }}</p>
                <hr>
            {% endfor %}

        </div>
      </div>
    </div>
  </div>
{% endblock %}

posts/templates/form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit">
    </form>
{% endblock%}

posts/templates/index.html
{% extends 'base.html' %}

{% block body %}
    <div class="row">

        {% for post in posts %}
            {% include '_card.html' %}
        {% endfor %}
    </div>
{% endblock %}

templates/_nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <i class="bi bi-instagram"></i></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          {% if user.is_authenticated%}
          <a class="nav-link" href="{% url 'posts:create' %}">Create</a>
          <a class="nav-link" href="{% url 'accounts:logout' %}">logout</a>
          <a class="nav-link disabled" aria-disabled="true">{{user}}</a>

          {% else %}
          <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
          <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>

          {% endif %}
        </div>
      </div>
    </div>
  </nav>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
<body>
    {% include '_nav.html' %}

    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

</body>
</html>